name = "micr-omega-worker"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787
local_protocol = "http"

[[routes]]
pattern = "realtime.micromundo.uk"
custom_domain = true

[vars]
# Adicione variáveis de ambiente compartilhadas aqui
# LOGFLARE_SOURCE_ID = ""
# LOGFLARE_API_TOKEN = ""

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true