name = "micr-omega-worker"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
# Adicione variáveis de ambiente compartilhadas aqui

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
