name = "micr-omega-worker"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

[vars]
# Adicione variáveis de ambiente compartilhadas aqui
# LOGFLARE_SOURCE_ID = ""
# LOGFLARE_API_TOKEN = ""

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDO"

routes = [
  { pattern = "realtime.example.com/ws", custom_domain = true }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
